2023-02-11 06:06:32,881 -  nornir.core -     INFO -        run() - Running task 'nuggets' with args {} on 7 hosts
2023-02-11 06:06:47,414 - nornir.core.task -    ERROR -      start() - Host 'R2': task 'napalm_configure' failed with traceback:
Traceback (most recent call last):
  File "/home/ipvzero/Netbox-Demo/.venv/lib/python3.10/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/ipvzero/Netbox-Demo/.venv/lib/python3.10/site-packages/nornir_napalm/plugins/tasks/napalm_configure.py", line 35, in napalm_configure
    device.load_merge_candidate(filename=filename, config=configuration)
  File "/home/ipvzero/Netbox-Demo/.venv/lib/python3.10/site-packages/napalm/ios/ios.py", line 317, in load_merge_candidate
    return_status, msg = self._load_candidate_wrapper(
  File "/home/ipvzero/Netbox-Demo/.venv/lib/python3.10/site-packages/napalm/ios/ios.py", line 284, in _load_candidate_wrapper
    (return_status, msg) = self._scp_file(
  File "/home/ipvzero/Netbox-Demo/.venv/lib/python3.10/site-packages/napalm/ios/ios.py", line 733, in _scp_file
    return self._xfer_file(
  File "/home/ipvzero/Netbox-Demo/.venv/lib/python3.10/site-packages/napalm/ios/ios.py", line 802, in _xfer_file
    raise CommandErrorException(msg)
napalm.base.exceptions.CommandErrorException: SCP file transfers are not enabled. Configure 'ip scp server enable' on the device.

2023-02-11 06:06:47,414 - nornir.core.task -    ERROR -      start() - Host 'R2': task 'nuggets' failed with traceback:
Traceback (most recent call last):
  File "/home/ipvzero/Netbox-Demo/.venv/lib/python3.10/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/ipvzero/Nornir/Dry_runs/runbook1-dry_run-send_config.py", line 13, in nuggets
    task.run(task=napalm_configure, filename="napalm-config.txt", dry_run=True)
  File "/home/ipvzero/Netbox-Demo/.venv/lib/python3.10/site-packages/nornir/core/task.py", line 174, in run
    raise NornirSubTaskError(task=run_task, result=r)
nornir.core.exceptions.NornirSubTaskError: Subtask: napalm_configure (failed)


2023-02-11 06:06:47,436 - nornir.core.task -    ERROR -      start() - Host 'R3': task 'napalm_configure' failed with traceback:
Traceback (most recent call last):
  File "/home/ipvzero/Netbox-Demo/.venv/lib/python3.10/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/ipvzero/Netbox-Demo/.venv/lib/python3.10/site-packages/nornir_napalm/plugins/tasks/napalm_configure.py", line 35, in napalm_configure
    device.load_merge_candidate(filename=filename, config=configuration)
  File "/home/ipvzero/Netbox-Demo/.venv/lib/python3.10/site-packages/napalm/ios/ios.py", line 317, in load_merge_candidate
    return_status, msg = self._load_candidate_wrapper(
  File "/home/ipvzero/Netbox-Demo/.venv/lib/python3.10/site-packages/napalm/ios/ios.py", line 284, in _load_candidate_wrapper
    (return_status, msg) = self._scp_file(
  File "/home/ipvzero/Netbox-Demo/.venv/lib/python3.10/site-packages/napalm/ios/ios.py", line 733, in _scp_file
    return self._xfer_file(
  File "/home/ipvzero/Netbox-Demo/.venv/lib/python3.10/site-packages/napalm/ios/ios.py", line 802, in _xfer_file
    raise CommandErrorException(msg)
napalm.base.exceptions.CommandErrorException: SCP file transfers are not enabled. Configure 'ip scp server enable' on the device.

2023-02-11 06:06:47,436 - nornir.core.task -    ERROR -      start() - Host 'R3': task 'nuggets' failed with traceback:
Traceback (most recent call last):
  File "/home/ipvzero/Netbox-Demo/.venv/lib/python3.10/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/ipvzero/Nornir/Dry_runs/runbook1-dry_run-send_config.py", line 13, in nuggets
    task.run(task=napalm_configure, filename="napalm-config.txt", dry_run=True)
  File "/home/ipvzero/Netbox-Demo/.venv/lib/python3.10/site-packages/nornir/core/task.py", line 174, in run
    raise NornirSubTaskError(task=run_task, result=r)
nornir.core.exceptions.NornirSubTaskError: Subtask: napalm_configure (failed)


2023-02-11 06:06:47,782 - nornir.core.task -    ERROR -      start() - Host 'R7': task 'napalm_configure' failed with traceback:
Traceback (most recent call last):
  File "/home/ipvzero/Netbox-Demo/.venv/lib/python3.10/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/ipvzero/Netbox-Demo/.venv/lib/python3.10/site-packages/nornir_napalm/plugins/tasks/napalm_configure.py", line 35, in napalm_configure
    device.load_merge_candidate(filename=filename, config=configuration)
  File "/home/ipvzero/Netbox-Demo/.venv/lib/python3.10/site-packages/napalm/ios/ios.py", line 317, in load_merge_candidate
    return_status, msg = self._load_candidate_wrapper(
  File "/home/ipvzero/Netbox-Demo/.venv/lib/python3.10/site-packages/napalm/ios/ios.py", line 284, in _load_candidate_wrapper
    (return_status, msg) = self._scp_file(
  File "/home/ipvzero/Netbox-Demo/.venv/lib/python3.10/site-packages/napalm/ios/ios.py", line 733, in _scp_file
    return self._xfer_file(
  File "/home/ipvzero/Netbox-Demo/.venv/lib/python3.10/site-packages/napalm/ios/ios.py", line 802, in _xfer_file
    raise CommandErrorException(msg)
napalm.base.exceptions.CommandErrorException: SCP file transfers are not enabled. Configure 'ip scp server enable' on the device.

2023-02-11 06:06:47,782 - nornir.core.task -    ERROR -      start() - Host 'R7': task 'nuggets' failed with traceback:
Traceback (most recent call last):
  File "/home/ipvzero/Netbox-Demo/.venv/lib/python3.10/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/ipvzero/Nornir/Dry_runs/runbook1-dry_run-send_config.py", line 13, in nuggets
    task.run(task=napalm_configure, filename="napalm-config.txt", dry_run=True)
  File "/home/ipvzero/Netbox-Demo/.venv/lib/python3.10/site-packages/nornir/core/task.py", line 174, in run
    raise NornirSubTaskError(task=run_task, result=r)
nornir.core.exceptions.NornirSubTaskError: Subtask: napalm_configure (failed)


2023-02-11 06:06:47,807 - nornir.core.task -    ERROR -      start() - Host 'R1': task 'napalm_configure' failed with traceback:
Traceback (most recent call last):
  File "/home/ipvzero/Netbox-Demo/.venv/lib/python3.10/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/ipvzero/Netbox-Demo/.venv/lib/python3.10/site-packages/nornir_napalm/plugins/tasks/napalm_configure.py", line 35, in napalm_configure
    device.load_merge_candidate(filename=filename, config=configuration)
  File "/home/ipvzero/Netbox-Demo/.venv/lib/python3.10/site-packages/napalm/ios/ios.py", line 317, in load_merge_candidate
    return_status, msg = self._load_candidate_wrapper(
  File "/home/ipvzero/Netbox-Demo/.venv/lib/python3.10/site-packages/napalm/ios/ios.py", line 284, in _load_candidate_wrapper
    (return_status, msg) = self._scp_file(
  File "/home/ipvzero/Netbox-Demo/.venv/lib/python3.10/site-packages/napalm/ios/ios.py", line 733, in _scp_file
    return self._xfer_file(
  File "/home/ipvzero/Netbox-Demo/.venv/lib/python3.10/site-packages/napalm/ios/ios.py", line 802, in _xfer_file
    raise CommandErrorException(msg)
napalm.base.exceptions.CommandErrorException: SCP file transfers are not enabled. Configure 'ip scp server enable' on the device.

2023-02-11 06:06:47,807 - nornir.core.task -    ERROR -      start() - Host 'R1': task 'nuggets' failed with traceback:
Traceback (most recent call last):
  File "/home/ipvzero/Netbox-Demo/.venv/lib/python3.10/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/ipvzero/Nornir/Dry_runs/runbook1-dry_run-send_config.py", line 13, in nuggets
    task.run(task=napalm_configure, filename="napalm-config.txt", dry_run=True)
  File "/home/ipvzero/Netbox-Demo/.venv/lib/python3.10/site-packages/nornir/core/task.py", line 174, in run
    raise NornirSubTaskError(task=run_task, result=r)
nornir.core.exceptions.NornirSubTaskError: Subtask: napalm_configure (failed)


2023-02-11 06:06:48,019 - nornir.core.task -    ERROR -      start() - Host 'R5': task 'napalm_configure' failed with traceback:
Traceback (most recent call last):
  File "/home/ipvzero/Netbox-Demo/.venv/lib/python3.10/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/ipvzero/Netbox-Demo/.venv/lib/python3.10/site-packages/nornir_napalm/plugins/tasks/napalm_configure.py", line 35, in napalm_configure
    device.load_merge_candidate(filename=filename, config=configuration)
  File "/home/ipvzero/Netbox-Demo/.venv/lib/python3.10/site-packages/napalm/ios/ios.py", line 317, in load_merge_candidate
    return_status, msg = self._load_candidate_wrapper(
  File "/home/ipvzero/Netbox-Demo/.venv/lib/python3.10/site-packages/napalm/ios/ios.py", line 284, in _load_candidate_wrapper
    (return_status, msg) = self._scp_file(
  File "/home/ipvzero/Netbox-Demo/.venv/lib/python3.10/site-packages/napalm/ios/ios.py", line 733, in _scp_file
    return self._xfer_file(
  File "/home/ipvzero/Netbox-Demo/.venv/lib/python3.10/site-packages/napalm/ios/ios.py", line 802, in _xfer_file
    raise CommandErrorException(msg)
napalm.base.exceptions.CommandErrorException: SCP file transfers are not enabled. Configure 'ip scp server enable' on the device.

2023-02-11 06:06:48,019 - nornir.core.task -    ERROR -      start() - Host 'R5': task 'nuggets' failed with traceback:
Traceback (most recent call last):
  File "/home/ipvzero/Netbox-Demo/.venv/lib/python3.10/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/ipvzero/Nornir/Dry_runs/runbook1-dry_run-send_config.py", line 13, in nuggets
    task.run(task=napalm_configure, filename="napalm-config.txt", dry_run=True)
  File "/home/ipvzero/Netbox-Demo/.venv/lib/python3.10/site-packages/nornir/core/task.py", line 174, in run
    raise NornirSubTaskError(task=run_task, result=r)
nornir.core.exceptions.NornirSubTaskError: Subtask: napalm_configure (failed)


2023-02-11 06:06:48,020 - nornir.core.task -    ERROR -      start() - Host 'R4': task 'napalm_configure' failed with traceback:
Traceback (most recent call last):
  File "/home/ipvzero/Netbox-Demo/.venv/lib/python3.10/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/ipvzero/Netbox-Demo/.venv/lib/python3.10/site-packages/nornir_napalm/plugins/tasks/napalm_configure.py", line 35, in napalm_configure
    device.load_merge_candidate(filename=filename, config=configuration)
  File "/home/ipvzero/Netbox-Demo/.venv/lib/python3.10/site-packages/napalm/ios/ios.py", line 317, in load_merge_candidate
    return_status, msg = self._load_candidate_wrapper(
  File "/home/ipvzero/Netbox-Demo/.venv/lib/python3.10/site-packages/napalm/ios/ios.py", line 284, in _load_candidate_wrapper
    (return_status, msg) = self._scp_file(
  File "/home/ipvzero/Netbox-Demo/.venv/lib/python3.10/site-packages/napalm/ios/ios.py", line 733, in _scp_file
    return self._xfer_file(
  File "/home/ipvzero/Netbox-Demo/.venv/lib/python3.10/site-packages/napalm/ios/ios.py", line 802, in _xfer_file
    raise CommandErrorException(msg)
napalm.base.exceptions.CommandErrorException: SCP file transfers are not enabled. Configure 'ip scp server enable' on the device.

2023-02-11 06:06:48,020 - nornir.core.task -    ERROR -      start() - Host 'R4': task 'nuggets' failed with traceback:
Traceback (most recent call last):
  File "/home/ipvzero/Netbox-Demo/.venv/lib/python3.10/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/ipvzero/Nornir/Dry_runs/runbook1-dry_run-send_config.py", line 13, in nuggets
    task.run(task=napalm_configure, filename="napalm-config.txt", dry_run=True)
  File "/home/ipvzero/Netbox-Demo/.venv/lib/python3.10/site-packages/nornir/core/task.py", line 174, in run
    raise NornirSubTaskError(task=run_task, result=r)
nornir.core.exceptions.NornirSubTaskError: Subtask: napalm_configure (failed)


2023-02-11 06:06:48,028 - nornir.core.task -    ERROR -      start() - Host 'R6': task 'napalm_configure' failed with traceback:
Traceback (most recent call last):
  File "/home/ipvzero/Netbox-Demo/.venv/lib/python3.10/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/ipvzero/Netbox-Demo/.venv/lib/python3.10/site-packages/nornir_napalm/plugins/tasks/napalm_configure.py", line 35, in napalm_configure
    device.load_merge_candidate(filename=filename, config=configuration)
  File "/home/ipvzero/Netbox-Demo/.venv/lib/python3.10/site-packages/napalm/ios/ios.py", line 317, in load_merge_candidate
    return_status, msg = self._load_candidate_wrapper(
  File "/home/ipvzero/Netbox-Demo/.venv/lib/python3.10/site-packages/napalm/ios/ios.py", line 284, in _load_candidate_wrapper
    (return_status, msg) = self._scp_file(
  File "/home/ipvzero/Netbox-Demo/.venv/lib/python3.10/site-packages/napalm/ios/ios.py", line 733, in _scp_file
    return self._xfer_file(
  File "/home/ipvzero/Netbox-Demo/.venv/lib/python3.10/site-packages/napalm/ios/ios.py", line 802, in _xfer_file
    raise CommandErrorException(msg)
napalm.base.exceptions.CommandErrorException: SCP file transfers are not enabled. Configure 'ip scp server enable' on the device.

2023-02-11 06:06:48,028 - nornir.core.task -    ERROR -      start() - Host 'R6': task 'nuggets' failed with traceback:
Traceback (most recent call last):
  File "/home/ipvzero/Netbox-Demo/.venv/lib/python3.10/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/ipvzero/Nornir/Dry_runs/runbook1-dry_run-send_config.py", line 13, in nuggets
    task.run(task=napalm_configure, filename="napalm-config.txt", dry_run=True)
  File "/home/ipvzero/Netbox-Demo/.venv/lib/python3.10/site-packages/nornir/core/task.py", line 174, in run
    raise NornirSubTaskError(task=run_task, result=r)
nornir.core.exceptions.NornirSubTaskError: Subtask: napalm_configure (failed)


2023-02-11 06:10:03,311 -  nornir.core -     INFO -        run() - Running task 'enable_scp' with args {} on 7 hosts
2023-02-11 06:10:12,510 -  nornir.core -     INFO -        run() - Running task 'nuggets' with args {} on 7 hosts
2023-02-11 06:10:26,240 - nornir.core.task -    ERROR -      start() - Host 'R7': task 'napalm_configure' failed with traceback:
Traceback (most recent call last):
  File "/home/ipvzero/Netbox-Demo/.venv/lib/python3.10/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/ipvzero/Netbox-Demo/.venv/lib/python3.10/site-packages/nornir_napalm/plugins/tasks/napalm_configure.py", line 35, in napalm_configure
    device.load_merge_candidate(filename=filename, config=configuration)
  File "/home/ipvzero/Netbox-Demo/.venv/lib/python3.10/site-packages/napalm/ios/ios.py", line 317, in load_merge_candidate
    return_status, msg = self._load_candidate_wrapper(
  File "/home/ipvzero/Netbox-Demo/.venv/lib/python3.10/site-packages/napalm/ios/ios.py", line 284, in _load_candidate_wrapper
    (return_status, msg) = self._scp_file(
  File "/home/ipvzero/Netbox-Demo/.venv/lib/python3.10/site-packages/napalm/ios/ios.py", line 733, in _scp_file
    return self._xfer_file(
  File "/home/ipvzero/Netbox-Demo/.venv/lib/python3.10/site-packages/napalm/ios/ios.py", line 805, in _xfer_file
    transfer.transfer_file()
  File "/home/ipvzero/Netbox-Demo/.venv/lib/python3.10/site-packages/netmiko/scp_handler.py", line 392, in transfer_file
    self.put_file()
  File "/home/ipvzero/Netbox-Demo/.venv/lib/python3.10/site-packages/netmiko/scp_handler.py", line 407, in put_file
    self.scp_conn.scp_transfer_file(self.source_file, destination)
  File "/home/ipvzero/Netbox-Demo/.venv/lib/python3.10/site-packages/netmiko/scp_handler.py", line 56, in scp_transfer_file
    self.scp_client.put(source_file, dest_file)
  File "/home/ipvzero/Netbox-Demo/.venv/lib/python3.10/site-packages/scp.py", line 195, in put
    self._recv_confirm()
  File "/home/ipvzero/Netbox-Demo/.venv/lib/python3.10/site-packages/scp.py", line 410, in _recv_confirm
    raise SCPException(asunicode(msg[1:]))
scp.SCPException: Authorization denied.


2023-02-11 06:10:26,241 - nornir.core.task -    ERROR -      start() - Host 'R7': task 'nuggets' failed with traceback:
Traceback (most recent call last):
  File "/home/ipvzero/Netbox-Demo/.venv/lib/python3.10/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/ipvzero/Nornir/Dry_runs/runbook1-dry_run-send_config.py", line 13, in nuggets
    task.run(task=napalm_configure, filename="napalm-config.txt", dry_run=True)
  File "/home/ipvzero/Netbox-Demo/.venv/lib/python3.10/site-packages/nornir/core/task.py", line 174, in run
    raise NornirSubTaskError(task=run_task, result=r)
nornir.core.exceptions.NornirSubTaskError: Subtask: napalm_configure (failed)


2023-02-11 06:10:26,883 - nornir.core.task -    ERROR -      start() - Host 'R6': task 'napalm_configure' failed with traceback:
Traceback (most recent call last):
  File "/home/ipvzero/Netbox-Demo/.venv/lib/python3.10/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/ipvzero/Netbox-Demo/.venv/lib/python3.10/site-packages/nornir_napalm/plugins/tasks/napalm_configure.py", line 35, in napalm_configure
    device.load_merge_candidate(filename=filename, config=configuration)
  File "/home/ipvzero/Netbox-Demo/.venv/lib/python3.10/site-packages/napalm/ios/ios.py", line 317, in load_merge_candidate
    return_status, msg = self._load_candidate_wrapper(
  File "/home/ipvzero/Netbox-Demo/.venv/lib/python3.10/site-packages/napalm/ios/ios.py", line 284, in _load_candidate_wrapper
    (return_status, msg) = self._scp_file(
  File "/home/ipvzero/Netbox-Demo/.venv/lib/python3.10/site-packages/napalm/ios/ios.py", line 733, in _scp_file
    return self._xfer_file(
  File "/home/ipvzero/Netbox-Demo/.venv/lib/python3.10/site-packages/napalm/ios/ios.py", line 805, in _xfer_file
    transfer.transfer_file()
  File "/home/ipvzero/Netbox-Demo/.venv/lib/python3.10/site-packages/netmiko/scp_handler.py", line 392, in transfer_file
    self.put_file()
  File "/home/ipvzero/Netbox-Demo/.venv/lib/python3.10/site-packages/netmiko/scp_handler.py", line 407, in put_file
    self.scp_conn.scp_transfer_file(self.source_file, destination)
  File "/home/ipvzero/Netbox-Demo/.venv/lib/python3.10/site-packages/netmiko/scp_handler.py", line 56, in scp_transfer_file
    self.scp_client.put(source_file, dest_file)
  File "/home/ipvzero/Netbox-Demo/.venv/lib/python3.10/site-packages/scp.py", line 195, in put
    self._recv_confirm()
  File "/home/ipvzero/Netbox-Demo/.venv/lib/python3.10/site-packages/scp.py", line 410, in _recv_confirm
    raise SCPException(asunicode(msg[1:]))
scp.SCPException: Authorization denied.


2023-02-11 06:10:26,883 - nornir.core.task -    ERROR -      start() - Host 'R6': task 'nuggets' failed with traceback:
Traceback (most recent call last):
  File "/home/ipvzero/Netbox-Demo/.venv/lib/python3.10/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/ipvzero/Nornir/Dry_runs/runbook1-dry_run-send_config.py", line 13, in nuggets
    task.run(task=napalm_configure, filename="napalm-config.txt", dry_run=True)
  File "/home/ipvzero/Netbox-Demo/.venv/lib/python3.10/site-packages/nornir/core/task.py", line 174, in run
    raise NornirSubTaskError(task=run_task, result=r)
nornir.core.exceptions.NornirSubTaskError: Subtask: napalm_configure (failed)


2023-02-11 06:15:48,072 -  nornir.core -     INFO -        run() - Running task 'nuggets' with args {} on 7 hosts
2023-02-11 06:16:02,037 - nornir.core.task -    ERROR -      start() - Host 'R7': task 'napalm_configure' failed with traceback:
Traceback (most recent call last):
  File "/home/ipvzero/Netbox-Demo/.venv/lib/python3.10/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/ipvzero/Netbox-Demo/.venv/lib/python3.10/site-packages/nornir_napalm/plugins/tasks/napalm_configure.py", line 35, in napalm_configure
    device.load_merge_candidate(filename=filename, config=configuration)
  File "/home/ipvzero/Netbox-Demo/.venv/lib/python3.10/site-packages/napalm/ios/ios.py", line 317, in load_merge_candidate
    return_status, msg = self._load_candidate_wrapper(
  File "/home/ipvzero/Netbox-Demo/.venv/lib/python3.10/site-packages/napalm/ios/ios.py", line 284, in _load_candidate_wrapper
    (return_status, msg) = self._scp_file(
  File "/home/ipvzero/Netbox-Demo/.venv/lib/python3.10/site-packages/napalm/ios/ios.py", line 733, in _scp_file
    return self._xfer_file(
  File "/home/ipvzero/Netbox-Demo/.venv/lib/python3.10/site-packages/napalm/ios/ios.py", line 805, in _xfer_file
    transfer.transfer_file()
  File "/home/ipvzero/Netbox-Demo/.venv/lib/python3.10/site-packages/netmiko/scp_handler.py", line 392, in transfer_file
    self.put_file()
  File "/home/ipvzero/Netbox-Demo/.venv/lib/python3.10/site-packages/netmiko/scp_handler.py", line 407, in put_file
    self.scp_conn.scp_transfer_file(self.source_file, destination)
  File "/home/ipvzero/Netbox-Demo/.venv/lib/python3.10/site-packages/netmiko/scp_handler.py", line 56, in scp_transfer_file
    self.scp_client.put(source_file, dest_file)
  File "/home/ipvzero/Netbox-Demo/.venv/lib/python3.10/site-packages/scp.py", line 195, in put
    self._recv_confirm()
  File "/home/ipvzero/Netbox-Demo/.venv/lib/python3.10/site-packages/scp.py", line 410, in _recv_confirm
    raise SCPException(asunicode(msg[1:]))
scp.SCPException: Authorization denied.


2023-02-11 06:16:02,037 - nornir.core.task -    ERROR -      start() - Host 'R7': task 'nuggets' failed with traceback:
Traceback (most recent call last):
  File "/home/ipvzero/Netbox-Demo/.venv/lib/python3.10/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/ipvzero/Nornir/Dry_runs/runbook1-dry_run-send_config.py", line 13, in nuggets
    task.run(task=napalm_configure, filename="napalm-config.txt", dry_run=True)
  File "/home/ipvzero/Netbox-Demo/.venv/lib/python3.10/site-packages/nornir/core/task.py", line 174, in run
    raise NornirSubTaskError(task=run_task, result=r)
nornir.core.exceptions.NornirSubTaskError: Subtask: napalm_configure (failed)


2023-02-11 06:16:04,374 - nornir.core.task -    ERROR -      start() - Host 'R6': task 'napalm_configure' failed with traceback:
Traceback (most recent call last):
  File "/home/ipvzero/Netbox-Demo/.venv/lib/python3.10/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/ipvzero/Netbox-Demo/.venv/lib/python3.10/site-packages/nornir_napalm/plugins/tasks/napalm_configure.py", line 35, in napalm_configure
    device.load_merge_candidate(filename=filename, config=configuration)
  File "/home/ipvzero/Netbox-Demo/.venv/lib/python3.10/site-packages/napalm/ios/ios.py", line 317, in load_merge_candidate
    return_status, msg = self._load_candidate_wrapper(
  File "/home/ipvzero/Netbox-Demo/.venv/lib/python3.10/site-packages/napalm/ios/ios.py", line 284, in _load_candidate_wrapper
    (return_status, msg) = self._scp_file(
  File "/home/ipvzero/Netbox-Demo/.venv/lib/python3.10/site-packages/napalm/ios/ios.py", line 733, in _scp_file
    return self._xfer_file(
  File "/home/ipvzero/Netbox-Demo/.venv/lib/python3.10/site-packages/napalm/ios/ios.py", line 805, in _xfer_file
    transfer.transfer_file()
  File "/home/ipvzero/Netbox-Demo/.venv/lib/python3.10/site-packages/netmiko/scp_handler.py", line 392, in transfer_file
    self.put_file()
  File "/home/ipvzero/Netbox-Demo/.venv/lib/python3.10/site-packages/netmiko/scp_handler.py", line 407, in put_file
    self.scp_conn.scp_transfer_file(self.source_file, destination)
  File "/home/ipvzero/Netbox-Demo/.venv/lib/python3.10/site-packages/netmiko/scp_handler.py", line 56, in scp_transfer_file
    self.scp_client.put(source_file, dest_file)
  File "/home/ipvzero/Netbox-Demo/.venv/lib/python3.10/site-packages/scp.py", line 195, in put
    self._recv_confirm()
  File "/home/ipvzero/Netbox-Demo/.venv/lib/python3.10/site-packages/scp.py", line 410, in _recv_confirm
    raise SCPException(asunicode(msg[1:]))
scp.SCPException: Authorization denied.


2023-02-11 06:16:04,374 - nornir.core.task -    ERROR -      start() - Host 'R6': task 'nuggets' failed with traceback:
Traceback (most recent call last):
  File "/home/ipvzero/Netbox-Demo/.venv/lib/python3.10/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/ipvzero/Nornir/Dry_runs/runbook1-dry_run-send_config.py", line 13, in nuggets
    task.run(task=napalm_configure, filename="napalm-config.txt", dry_run=True)
  File "/home/ipvzero/Netbox-Demo/.venv/lib/python3.10/site-packages/nornir/core/task.py", line 174, in run
    raise NornirSubTaskError(task=run_task, result=r)
nornir.core.exceptions.NornirSubTaskError: Subtask: napalm_configure (failed)


2023-02-11 06:27:00,718 -  nornir.core -     INFO -        run() - Running task 'nuggets' with args {} on 7 hosts
2023-02-11 06:27:15,235 - nornir.core.task -    ERROR -      start() - Host 'R6': task 'napalm_configure' failed with traceback:
Traceback (most recent call last):
  File "/home/ipvzero/Nornir/.venv/lib/python3.10/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/ipvzero/Nornir/.venv/lib/python3.10/site-packages/nornir_napalm/plugins/tasks/napalm_configure.py", line 35, in napalm_configure
    device.load_merge_candidate(filename=filename, config=configuration)
  File "/home/ipvzero/Nornir/.venv/lib/python3.10/site-packages/napalm/ios/ios.py", line 317, in load_merge_candidate
    return_status, msg = self._load_candidate_wrapper(
  File "/home/ipvzero/Nornir/.venv/lib/python3.10/site-packages/napalm/ios/ios.py", line 284, in _load_candidate_wrapper
    (return_status, msg) = self._scp_file(
  File "/home/ipvzero/Nornir/.venv/lib/python3.10/site-packages/napalm/ios/ios.py", line 733, in _scp_file
    return self._xfer_file(
  File "/home/ipvzero/Nornir/.venv/lib/python3.10/site-packages/napalm/ios/ios.py", line 805, in _xfer_file
    transfer.transfer_file()
  File "/home/ipvzero/Nornir/.venv/lib/python3.10/site-packages/netmiko/scp_handler.py", line 392, in transfer_file
    self.put_file()
  File "/home/ipvzero/Nornir/.venv/lib/python3.10/site-packages/netmiko/scp_handler.py", line 407, in put_file
    self.scp_conn.scp_transfer_file(self.source_file, destination)
  File "/home/ipvzero/Nornir/.venv/lib/python3.10/site-packages/netmiko/scp_handler.py", line 56, in scp_transfer_file
    self.scp_client.put(source_file, dest_file)
  File "/home/ipvzero/Nornir/.venv/lib/python3.10/site-packages/scp.py", line 191, in put
    self._recv_confirm()
  File "/home/ipvzero/Nornir/.venv/lib/python3.10/site-packages/scp.py", line 404, in _recv_confirm
    raise SCPException(asunicode(msg[1:]))
scp.SCPException: Authorization denied.


2023-02-11 06:27:15,236 - nornir.core.task -    ERROR -      start() - Host 'R6': task 'nuggets' failed with traceback:
Traceback (most recent call last):
  File "/home/ipvzero/Nornir/.venv/lib/python3.10/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/ipvzero/Nornir/Dry_runs/runbook1-dry_run-send_config.py", line 13, in nuggets
    task.run(task=napalm_configure, filename="napalm-config.txt", dry_run=True)
  File "/home/ipvzero/Nornir/.venv/lib/python3.10/site-packages/nornir/core/task.py", line 174, in run
    raise NornirSubTaskError(task=run_task, result=r)
nornir.core.exceptions.NornirSubTaskError: Subtask: napalm_configure (failed)


2023-02-11 06:27:16,914 - nornir.core.task -    ERROR -      start() - Host 'R7': task 'napalm_configure' failed with traceback:
Traceback (most recent call last):
  File "/home/ipvzero/Nornir/.venv/lib/python3.10/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/ipvzero/Nornir/.venv/lib/python3.10/site-packages/nornir_napalm/plugins/tasks/napalm_configure.py", line 35, in napalm_configure
    device.load_merge_candidate(filename=filename, config=configuration)
  File "/home/ipvzero/Nornir/.venv/lib/python3.10/site-packages/napalm/ios/ios.py", line 317, in load_merge_candidate
    return_status, msg = self._load_candidate_wrapper(
  File "/home/ipvzero/Nornir/.venv/lib/python3.10/site-packages/napalm/ios/ios.py", line 284, in _load_candidate_wrapper
    (return_status, msg) = self._scp_file(
  File "/home/ipvzero/Nornir/.venv/lib/python3.10/site-packages/napalm/ios/ios.py", line 733, in _scp_file
    return self._xfer_file(
  File "/home/ipvzero/Nornir/.venv/lib/python3.10/site-packages/napalm/ios/ios.py", line 805, in _xfer_file
    transfer.transfer_file()
  File "/home/ipvzero/Nornir/.venv/lib/python3.10/site-packages/netmiko/scp_handler.py", line 392, in transfer_file
    self.put_file()
  File "/home/ipvzero/Nornir/.venv/lib/python3.10/site-packages/netmiko/scp_handler.py", line 407, in put_file
    self.scp_conn.scp_transfer_file(self.source_file, destination)
  File "/home/ipvzero/Nornir/.venv/lib/python3.10/site-packages/netmiko/scp_handler.py", line 56, in scp_transfer_file
    self.scp_client.put(source_file, dest_file)
  File "/home/ipvzero/Nornir/.venv/lib/python3.10/site-packages/scp.py", line 191, in put
    self._recv_confirm()
  File "/home/ipvzero/Nornir/.venv/lib/python3.10/site-packages/scp.py", line 404, in _recv_confirm
    raise SCPException(asunicode(msg[1:]))
scp.SCPException: Authorization denied.


2023-02-11 06:27:16,914 - nornir.core.task -    ERROR -      start() - Host 'R7': task 'nuggets' failed with traceback:
Traceback (most recent call last):
  File "/home/ipvzero/Nornir/.venv/lib/python3.10/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/ipvzero/Nornir/Dry_runs/runbook1-dry_run-send_config.py", line 13, in nuggets
    task.run(task=napalm_configure, filename="napalm-config.txt", dry_run=True)
  File "/home/ipvzero/Nornir/.venv/lib/python3.10/site-packages/nornir/core/task.py", line 174, in run
    raise NornirSubTaskError(task=run_task, result=r)
nornir.core.exceptions.NornirSubTaskError: Subtask: napalm_configure (failed)


2023-02-11 06:30:01,925 -  nornir.core -     INFO -        run() - Running task 'nuggets' with args {} on 7 hosts
2023-02-11 06:30:15,812 - nornir.core.task -    ERROR -      start() - Host 'R6': task 'napalm_configure' failed with traceback:
Traceback (most recent call last):
  File "/home/ipvzero/Nornir/.venv/lib/python3.10/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/ipvzero/Nornir/.venv/lib/python3.10/site-packages/nornir_napalm/plugins/tasks/napalm_configure.py", line 35, in napalm_configure
    device.load_merge_candidate(filename=filename, config=configuration)
  File "/home/ipvzero/Nornir/.venv/lib/python3.10/site-packages/napalm/ios/ios.py", line 317, in load_merge_candidate
    return_status, msg = self._load_candidate_wrapper(
  File "/home/ipvzero/Nornir/.venv/lib/python3.10/site-packages/napalm/ios/ios.py", line 284, in _load_candidate_wrapper
    (return_status, msg) = self._scp_file(
  File "/home/ipvzero/Nornir/.venv/lib/python3.10/site-packages/napalm/ios/ios.py", line 733, in _scp_file
    return self._xfer_file(
  File "/home/ipvzero/Nornir/.venv/lib/python3.10/site-packages/napalm/ios/ios.py", line 805, in _xfer_file
    transfer.transfer_file()
  File "/home/ipvzero/Nornir/.venv/lib/python3.10/site-packages/netmiko/scp_handler.py", line 392, in transfer_file
    self.put_file()
  File "/home/ipvzero/Nornir/.venv/lib/python3.10/site-packages/netmiko/scp_handler.py", line 407, in put_file
    self.scp_conn.scp_transfer_file(self.source_file, destination)
  File "/home/ipvzero/Nornir/.venv/lib/python3.10/site-packages/netmiko/scp_handler.py", line 56, in scp_transfer_file
    self.scp_client.put(source_file, dest_file)
  File "/home/ipvzero/Nornir/.venv/lib/python3.10/site-packages/scp.py", line 191, in put
    self._recv_confirm()
  File "/home/ipvzero/Nornir/.venv/lib/python3.10/site-packages/scp.py", line 404, in _recv_confirm
    raise SCPException(asunicode(msg[1:]))
scp.SCPException: Authorization denied.


2023-02-11 06:30:15,812 - nornir.core.task -    ERROR -      start() - Host 'R6': task 'nuggets' failed with traceback:
Traceback (most recent call last):
  File "/home/ipvzero/Nornir/.venv/lib/python3.10/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/ipvzero/Nornir/Dry_runs/runbook1-dry_run-send_config.py", line 13, in nuggets
    task.run(task=napalm_configure, filename="napalm-config.txt", dry_run=True)
  File "/home/ipvzero/Nornir/.venv/lib/python3.10/site-packages/nornir/core/task.py", line 174, in run
    raise NornirSubTaskError(task=run_task, result=r)
nornir.core.exceptions.NornirSubTaskError: Subtask: napalm_configure (failed)


2023-02-11 06:30:16,178 - nornir.core.task -    ERROR -      start() - Host 'R7': task 'napalm_configure' failed with traceback:
Traceback (most recent call last):
  File "/home/ipvzero/Nornir/.venv/lib/python3.10/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/ipvzero/Nornir/.venv/lib/python3.10/site-packages/nornir_napalm/plugins/tasks/napalm_configure.py", line 35, in napalm_configure
    device.load_merge_candidate(filename=filename, config=configuration)
  File "/home/ipvzero/Nornir/.venv/lib/python3.10/site-packages/napalm/ios/ios.py", line 317, in load_merge_candidate
    return_status, msg = self._load_candidate_wrapper(
  File "/home/ipvzero/Nornir/.venv/lib/python3.10/site-packages/napalm/ios/ios.py", line 284, in _load_candidate_wrapper
    (return_status, msg) = self._scp_file(
  File "/home/ipvzero/Nornir/.venv/lib/python3.10/site-packages/napalm/ios/ios.py", line 733, in _scp_file
    return self._xfer_file(
  File "/home/ipvzero/Nornir/.venv/lib/python3.10/site-packages/napalm/ios/ios.py", line 805, in _xfer_file
    transfer.transfer_file()
  File "/home/ipvzero/Nornir/.venv/lib/python3.10/site-packages/netmiko/scp_handler.py", line 392, in transfer_file
    self.put_file()
  File "/home/ipvzero/Nornir/.venv/lib/python3.10/site-packages/netmiko/scp_handler.py", line 407, in put_file
    self.scp_conn.scp_transfer_file(self.source_file, destination)
  File "/home/ipvzero/Nornir/.venv/lib/python3.10/site-packages/netmiko/scp_handler.py", line 56, in scp_transfer_file
    self.scp_client.put(source_file, dest_file)
  File "/home/ipvzero/Nornir/.venv/lib/python3.10/site-packages/scp.py", line 191, in put
    self._recv_confirm()
  File "/home/ipvzero/Nornir/.venv/lib/python3.10/site-packages/scp.py", line 404, in _recv_confirm
    raise SCPException(asunicode(msg[1:]))
scp.SCPException: Authorization denied.


2023-02-11 06:30:16,179 - nornir.core.task -    ERROR -      start() - Host 'R7': task 'nuggets' failed with traceback:
Traceback (most recent call last):
  File "/home/ipvzero/Nornir/.venv/lib/python3.10/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/ipvzero/Nornir/Dry_runs/runbook1-dry_run-send_config.py", line 13, in nuggets
    task.run(task=napalm_configure, filename="napalm-config.txt", dry_run=True)
  File "/home/ipvzero/Nornir/.venv/lib/python3.10/site-packages/nornir/core/task.py", line 174, in run
    raise NornirSubTaskError(task=run_task, result=r)
nornir.core.exceptions.NornirSubTaskError: Subtask: napalm_configure (failed)


2023-02-11 06:32:57,327 -  nornir.core -     INFO -        run() - Running task 'nuggets' with args {} on 7 hosts
2023-02-11 06:33:09,940 - nornir.core.task -    ERROR -      start() - Host 'R7': task 'napalm_configure' failed with traceback:
Traceback (most recent call last):
  File "/home/ipvzero/Nornir/.venv/lib/python3.10/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/ipvzero/Nornir/.venv/lib/python3.10/site-packages/nornir_napalm/plugins/tasks/napalm_configure.py", line 35, in napalm_configure
    device.load_merge_candidate(filename=filename, config=configuration)
  File "/home/ipvzero/Nornir/.venv/lib/python3.10/site-packages/napalm/ios/ios.py", line 317, in load_merge_candidate
    return_status, msg = self._load_candidate_wrapper(
  File "/home/ipvzero/Nornir/.venv/lib/python3.10/site-packages/napalm/ios/ios.py", line 284, in _load_candidate_wrapper
    (return_status, msg) = self._scp_file(
  File "/home/ipvzero/Nornir/.venv/lib/python3.10/site-packages/napalm/ios/ios.py", line 733, in _scp_file
    return self._xfer_file(
  File "/home/ipvzero/Nornir/.venv/lib/python3.10/site-packages/napalm/ios/ios.py", line 805, in _xfer_file
    transfer.transfer_file()
  File "/home/ipvzero/Nornir/.venv/lib/python3.10/site-packages/netmiko/scp_handler.py", line 392, in transfer_file
    self.put_file()
  File "/home/ipvzero/Nornir/.venv/lib/python3.10/site-packages/netmiko/scp_handler.py", line 407, in put_file
    self.scp_conn.scp_transfer_file(self.source_file, destination)
  File "/home/ipvzero/Nornir/.venv/lib/python3.10/site-packages/netmiko/scp_handler.py", line 56, in scp_transfer_file
    self.scp_client.put(source_file, dest_file)
  File "/home/ipvzero/Nornir/.venv/lib/python3.10/site-packages/scp.py", line 191, in put
    self._recv_confirm()
  File "/home/ipvzero/Nornir/.venv/lib/python3.10/site-packages/scp.py", line 404, in _recv_confirm
    raise SCPException(asunicode(msg[1:]))
scp.SCPException: Authorization denied.


2023-02-11 06:33:09,940 - nornir.core.task -    ERROR -      start() - Host 'R7': task 'nuggets' failed with traceback:
Traceback (most recent call last):
  File "/home/ipvzero/Nornir/.venv/lib/python3.10/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/ipvzero/Nornir/Dry_runs/runbook1-dry_run-send_config.py", line 13, in nuggets
    task.run(task=napalm_configure, filename="napalm-config.txt", dry_run=True)
  File "/home/ipvzero/Nornir/.venv/lib/python3.10/site-packages/nornir/core/task.py", line 174, in run
    raise NornirSubTaskError(task=run_task, result=r)
nornir.core.exceptions.NornirSubTaskError: Subtask: napalm_configure (failed)


2023-02-11 06:33:11,962 - nornir.core.task -    ERROR -      start() - Host 'R6': task 'napalm_configure' failed with traceback:
Traceback (most recent call last):
  File "/home/ipvzero/Nornir/.venv/lib/python3.10/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/ipvzero/Nornir/.venv/lib/python3.10/site-packages/nornir_napalm/plugins/tasks/napalm_configure.py", line 35, in napalm_configure
    device.load_merge_candidate(filename=filename, config=configuration)
  File "/home/ipvzero/Nornir/.venv/lib/python3.10/site-packages/napalm/ios/ios.py", line 317, in load_merge_candidate
    return_status, msg = self._load_candidate_wrapper(
  File "/home/ipvzero/Nornir/.venv/lib/python3.10/site-packages/napalm/ios/ios.py", line 284, in _load_candidate_wrapper
    (return_status, msg) = self._scp_file(
  File "/home/ipvzero/Nornir/.venv/lib/python3.10/site-packages/napalm/ios/ios.py", line 733, in _scp_file
    return self._xfer_file(
  File "/home/ipvzero/Nornir/.venv/lib/python3.10/site-packages/napalm/ios/ios.py", line 805, in _xfer_file
    transfer.transfer_file()
  File "/home/ipvzero/Nornir/.venv/lib/python3.10/site-packages/netmiko/scp_handler.py", line 392, in transfer_file
    self.put_file()
  File "/home/ipvzero/Nornir/.venv/lib/python3.10/site-packages/netmiko/scp_handler.py", line 407, in put_file
    self.scp_conn.scp_transfer_file(self.source_file, destination)
  File "/home/ipvzero/Nornir/.venv/lib/python3.10/site-packages/netmiko/scp_handler.py", line 56, in scp_transfer_file
    self.scp_client.put(source_file, dest_file)
  File "/home/ipvzero/Nornir/.venv/lib/python3.10/site-packages/scp.py", line 191, in put
    self._recv_confirm()
  File "/home/ipvzero/Nornir/.venv/lib/python3.10/site-packages/scp.py", line 404, in _recv_confirm
    raise SCPException(asunicode(msg[1:]))
scp.SCPException: Authorization denied.


2023-02-11 06:33:11,962 - nornir.core.task -    ERROR -      start() - Host 'R6': task 'nuggets' failed with traceback:
Traceback (most recent call last):
  File "/home/ipvzero/Nornir/.venv/lib/python3.10/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/ipvzero/Nornir/Dry_runs/runbook1-dry_run-send_config.py", line 13, in nuggets
    task.run(task=napalm_configure, filename="napalm-config.txt", dry_run=True)
  File "/home/ipvzero/Nornir/.venv/lib/python3.10/site-packages/nornir/core/task.py", line 174, in run
    raise NornirSubTaskError(task=run_task, result=r)
nornir.core.exceptions.NornirSubTaskError: Subtask: napalm_configure (failed)


2023-02-11 06:46:07,056 -  nornir.core -     INFO -        run() - Running task 'nuggets' with args {} on 5 hosts
2023-02-11 06:49:06,496 -  nornir.core -     INFO -        run() - Running task 'nuggets' with args {} on 5 hosts
2023-02-11 06:52:56,689 -  nornir.core -     INFO -        run() - Running task 'nuggets' with args {'progress_bar': <tqdm.std.tqdm object at 0x7efe887c4070>} on 5 hosts
2023-02-11 06:53:24,604 -  nornir.core -     INFO -        run() - Running task 'nuggets' with args {} on 5 hosts
2023-02-11 06:53:24,605 - nornir.core.task -    ERROR -      start() - Host 'R1': task 'nuggets' failed with traceback:
Traceback (most recent call last):
  File "/home/ipvzero/Nornir/.venv/lib/python3.10/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
TypeError: nuggets() missing 1 required positional argument: 'progress_bar'

2023-02-11 06:53:24,605 - nornir.core.task -    ERROR -      start() - Host 'R2': task 'nuggets' failed with traceback:
Traceback (most recent call last):
  File "/home/ipvzero/Nornir/.venv/lib/python3.10/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
TypeError: nuggets() missing 1 required positional argument: 'progress_bar'

2023-02-11 06:53:24,606 - nornir.core.task -    ERROR -      start() - Host 'R3': task 'nuggets' failed with traceback:
Traceback (most recent call last):
  File "/home/ipvzero/Nornir/.venv/lib/python3.10/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
TypeError: nuggets() missing 1 required positional argument: 'progress_bar'

2023-02-11 06:53:24,606 - nornir.core.task -    ERROR -      start() - Host 'R4': task 'nuggets' failed with traceback:
Traceback (most recent call last):
  File "/home/ipvzero/Nornir/.venv/lib/python3.10/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
TypeError: nuggets() missing 1 required positional argument: 'progress_bar'

2023-02-11 06:53:24,606 - nornir.core.task -    ERROR -      start() - Host 'R5': task 'nuggets' failed with traceback:
Traceback (most recent call last):
  File "/home/ipvzero/Nornir/.venv/lib/python3.10/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
TypeError: nuggets() missing 1 required positional argument: 'progress_bar'

2023-02-11 07:02:27,395 -  nornir.core -     INFO -        run() - Running task 'nuggets' with args {} on 5 hosts
2023-02-11 07:03:21,471 -  nornir.core -     INFO -        run() - Running task 'nuggets' with args {} on 5 hosts
2023-02-11 07:05:52,549 -  nornir.core -     INFO -        run() - Running task 'nuggets' with args {'progress_bar': <tqdm.std.tqdm object at 0x7f8390dd44f0>} on 5 hosts
2023-02-11 07:06:22,829 -  nornir.core -     INFO -        run() - Running task 'nuggets' with args {} on 5 hosts
2023-02-11 07:06:22,830 - nornir.core.task -    ERROR -      start() - Host 'R1': task 'nuggets' failed with traceback:
Traceback (most recent call last):
  File "/home/ipvzero/Nornir/.venv/lib/python3.10/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
TypeError: nuggets() missing 1 required positional argument: 'progress_bar'

2023-02-11 07:06:22,830 - nornir.core.task -    ERROR -      start() - Host 'R2': task 'nuggets' failed with traceback:
Traceback (most recent call last):
  File "/home/ipvzero/Nornir/.venv/lib/python3.10/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
TypeError: nuggets() missing 1 required positional argument: 'progress_bar'

2023-02-11 07:06:22,831 - nornir.core.task -    ERROR -      start() - Host 'R3': task 'nuggets' failed with traceback:
Traceback (most recent call last):
  File "/home/ipvzero/Nornir/.venv/lib/python3.10/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
TypeError: nuggets() missing 1 required positional argument: 'progress_bar'

2023-02-11 07:06:22,831 - nornir.core.task -    ERROR -      start() - Host 'R4': task 'nuggets' failed with traceback:
Traceback (most recent call last):
  File "/home/ipvzero/Nornir/.venv/lib/python3.10/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
TypeError: nuggets() missing 1 required positional argument: 'progress_bar'

2023-02-11 07:06:22,832 - nornir.core.task -    ERROR -      start() - Host 'R5': task 'nuggets' failed with traceback:
Traceback (most recent call last):
  File "/home/ipvzero/Nornir/.venv/lib/python3.10/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
TypeError: nuggets() missing 1 required positional argument: 'progress_bar'

2023-02-11 07:12:39,332 -  nornir.core -     INFO -        run() - Running task 'nuggets' with args {'progress_bar': <tqdm.std.tqdm object at 0x7fe4b35d8070>} on 5 hosts
2023-02-11 07:13:13,391 -  nornir.core -     INFO -        run() - Running task 'nuggets' with args {} on 5 hosts
2023-02-11 07:13:13,392 - nornir.core.task -    ERROR -      start() - Host 'R2': task 'nuggets' failed with traceback:
Traceback (most recent call last):
  File "/home/ipvzero/Nornir/.venv/lib/python3.10/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
TypeError: nuggets() missing 1 required positional argument: 'progress_bar'

2023-02-11 07:13:13,392 - nornir.core.task -    ERROR -      start() - Host 'R3': task 'nuggets' failed with traceback:
Traceback (most recent call last):
  File "/home/ipvzero/Nornir/.venv/lib/python3.10/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
TypeError: nuggets() missing 1 required positional argument: 'progress_bar'

2023-02-11 07:13:13,392 - nornir.core.task -    ERROR -      start() - Host 'R4': task 'nuggets' failed with traceback:
Traceback (most recent call last):
  File "/home/ipvzero/Nornir/.venv/lib/python3.10/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
TypeError: nuggets() missing 1 required positional argument: 'progress_bar'

2023-02-11 07:13:13,392 - nornir.core.task -    ERROR -      start() - Host 'R5': task 'nuggets' failed with traceback:
Traceback (most recent call last):
  File "/home/ipvzero/Nornir/.venv/lib/python3.10/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
TypeError: nuggets() missing 1 required positional argument: 'progress_bar'

2023-02-11 07:13:13,393 - nornir.core.task -    ERROR -      start() - Host 'R1': task 'nuggets' failed with traceback:
Traceback (most recent call last):
  File "/home/ipvzero/Nornir/.venv/lib/python3.10/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
TypeError: nuggets() missing 1 required positional argument: 'progress_bar'

2023-02-11 07:13:41,204 -  nornir.core -     INFO -        run() - Running task 'nuggets' with args {} on 5 hosts
