2023-02-12 07:51:47,000 -  nornir.core -     INFO -        run() - Running task 'banner_push' with args {} on 2 hosts
2023-02-12 07:51:47,095 - nornir.core.task -    ERROR -      start() - Host 'R1(Tigerwoods)': task 'Configuring Banner' failed with traceback:
Traceback (most recent call last):
  File "/home/ipvzero/Nornir/.venv/lib/python3.10/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/ipvzero/Nornir/.venv/lib/python3.10/site-packages/nornir_scrapli/tasks/core/send_configs_from_file.py", line 58, in send_configs_from_file
    scrapli_conn = task.host.get_connection("scrapli", task.nornir.config)
  File "/home/ipvzero/Nornir/.venv/lib/python3.10/site-packages/nornir/core/inventory.py", line 494, in get_connection
    self.open_connection(
  File "/home/ipvzero/Nornir/.venv/lib/python3.10/site-packages/nornir/core/inventory.py", line 546, in open_connection
    conn_obj.open(
  File "/home/ipvzero/Nornir/.venv/lib/python3.10/site-packages/nornir_scrapli/connection.py", line 88, in open
    raise NornirScrapliInvalidPlatform(
nornir_scrapli.exceptions.NornirScrapliInvalidPlatform: 'platform' not provided in inventory for host `192.168.179.130`

2023-02-12 07:51:47,096 - nornir.core.task -    ERROR -      start() - Host 'R1(Tigerwoods)': task 'banner_push' failed with traceback:
Traceback (most recent call last):
  File "/home/ipvzero/Nornir/.venv/lib/python3.10/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/ipvzero/Nornir/F_object/run1-F_object-filtering.py", line 17, in banner_push
    task.run(task=send_configs_from_file, name="Configuring Banner", file="reader.txt")
  File "/home/ipvzero/Nornir/.venv/lib/python3.10/site-packages/nornir/core/task.py", line 174, in run
    raise NornirSubTaskError(task=run_task, result=r)
nornir.core.exceptions.NornirSubTaskError: Subtask: Configuring Banner (failed)


2023-02-12 07:51:47,096 - nornir.core.task -    ERROR -      start() - Host 'R5(MarieCurie)': task 'Configuring Banner' failed with traceback:
Traceback (most recent call last):
  File "/home/ipvzero/Nornir/.venv/lib/python3.10/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/ipvzero/Nornir/.venv/lib/python3.10/site-packages/nornir_scrapli/tasks/core/send_configs_from_file.py", line 58, in send_configs_from_file
    scrapli_conn = task.host.get_connection("scrapli", task.nornir.config)
  File "/home/ipvzero/Nornir/.venv/lib/python3.10/site-packages/nornir/core/inventory.py", line 494, in get_connection
    self.open_connection(
  File "/home/ipvzero/Nornir/.venv/lib/python3.10/site-packages/nornir/core/inventory.py", line 546, in open_connection
    conn_obj.open(
  File "/home/ipvzero/Nornir/.venv/lib/python3.10/site-packages/nornir_scrapli/connection.py", line 88, in open
    raise NornirScrapliInvalidPlatform(
nornir_scrapli.exceptions.NornirScrapliInvalidPlatform: 'platform' not provided in inventory for host `192.168.179.134`

2023-02-12 07:51:47,096 - nornir.core.task -    ERROR -      start() - Host 'R5(MarieCurie)': task 'banner_push' failed with traceback:
Traceback (most recent call last):
  File "/home/ipvzero/Nornir/.venv/lib/python3.10/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/ipvzero/Nornir/F_object/run1-F_object-filtering.py", line 17, in banner_push
    task.run(task=send_configs_from_file, name="Configuring Banner", file="reader.txt")
  File "/home/ipvzero/Nornir/.venv/lib/python3.10/site-packages/nornir/core/task.py", line 174, in run
    raise NornirSubTaskError(task=run_task, result=r)
nornir.core.exceptions.NornirSubTaskError: Subtask: Configuring Banner (failed)


2023-02-12 07:54:39,473 -  nornir.core -     INFO -        run() - Running task 'banner_push' with args {} on 2 hosts
2023-02-12 07:54:43,986 - nornir.core.task -    ERROR -      start() - Host 'R1(Tigerwoods)': task 'Configuring Banner' failed with traceback:
Traceback (most recent call last):
  File "/home/ipvzero/Nornir/.venv/lib/python3.10/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/ipvzero/Nornir/.venv/lib/python3.10/site-packages/nornir_scrapli/tasks/core/send_configs_from_file.py", line 58, in send_configs_from_file
    scrapli_conn = task.host.get_connection("scrapli", task.nornir.config)
  File "/home/ipvzero/Nornir/.venv/lib/python3.10/site-packages/nornir/core/inventory.py", line 494, in get_connection
    self.open_connection(
  File "/home/ipvzero/Nornir/.venv/lib/python3.10/site-packages/nornir/core/inventory.py", line 546, in open_connection
    conn_obj.open(
  File "/home/ipvzero/Nornir/.venv/lib/python3.10/site-packages/nornir_scrapli/connection.py", line 105, in open
    connection.open()
  File "/home/ipvzero/Nornir/.venv/lib/python3.10/site-packages/scrapli/driver/base/sync_driver.py", line 88, in open
    self.channel.channel_authenticate_ssh(
  File "/home/ipvzero/Nornir/.venv/lib/python3.10/site-packages/scrapli/decorators.py", line 216, in decorate
    return _multiprocessing_timeout(
  File "/home/ipvzero/Nornir/.venv/lib/python3.10/site-packages/scrapli/decorators.py", line 113, in _multiprocessing_timeout
    return future.result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/ipvzero/Nornir/.venv/lib/python3.10/site-packages/scrapli/channel/sync_channel.py", line 302, in channel_authenticate_ssh
    raise ScrapliAuthenticationFailed(msg)
scrapli.exceptions.ScrapliAuthenticationFailed: password prompt seen more than once, assuming auth failed

2023-02-12 07:54:43,996 - nornir.core.task -    ERROR -      start() - Host 'R1(Tigerwoods)': task 'banner_push' failed with traceback:
Traceback (most recent call last):
  File "/home/ipvzero/Nornir/.venv/lib/python3.10/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/ipvzero/Nornir/F_object/run1-F_object-filtering.py", line 17, in banner_push
    task.run(task=send_configs_from_file, name="Configuring Banner", file="reader.txt")
  File "/home/ipvzero/Nornir/.venv/lib/python3.10/site-packages/nornir/core/task.py", line 174, in run
    raise NornirSubTaskError(task=run_task, result=r)
nornir.core.exceptions.NornirSubTaskError: Subtask: Configuring Banner (failed)


2023-02-12 07:54:46,251 - nornir.core.task -    ERROR -      start() - Host 'R5(MarieCurie)': task 'Configuring Banner' failed with traceback:
Traceback (most recent call last):
  File "/home/ipvzero/Nornir/.venv/lib/python3.10/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/ipvzero/Nornir/.venv/lib/python3.10/site-packages/nornir_scrapli/tasks/core/send_configs_from_file.py", line 58, in send_configs_from_file
    scrapli_conn = task.host.get_connection("scrapli", task.nornir.config)
  File "/home/ipvzero/Nornir/.venv/lib/python3.10/site-packages/nornir/core/inventory.py", line 494, in get_connection
    self.open_connection(
  File "/home/ipvzero/Nornir/.venv/lib/python3.10/site-packages/nornir/core/inventory.py", line 546, in open_connection
    conn_obj.open(
  File "/home/ipvzero/Nornir/.venv/lib/python3.10/site-packages/nornir_scrapli/connection.py", line 105, in open
    connection.open()
  File "/home/ipvzero/Nornir/.venv/lib/python3.10/site-packages/scrapli/driver/base/sync_driver.py", line 88, in open
    self.channel.channel_authenticate_ssh(
  File "/home/ipvzero/Nornir/.venv/lib/python3.10/site-packages/scrapli/decorators.py", line 216, in decorate
    return _multiprocessing_timeout(
  File "/home/ipvzero/Nornir/.venv/lib/python3.10/site-packages/scrapli/decorators.py", line 113, in _multiprocessing_timeout
    return future.result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/ipvzero/Nornir/.venv/lib/python3.10/site-packages/scrapli/channel/sync_channel.py", line 302, in channel_authenticate_ssh
    raise ScrapliAuthenticationFailed(msg)
scrapli.exceptions.ScrapliAuthenticationFailed: password prompt seen more than once, assuming auth failed

2023-02-12 07:54:46,251 - nornir.core.task -    ERROR -      start() - Host 'R5(MarieCurie)': task 'banner_push' failed with traceback:
Traceback (most recent call last):
  File "/home/ipvzero/Nornir/.venv/lib/python3.10/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/ipvzero/Nornir/F_object/run1-F_object-filtering.py", line 17, in banner_push
    task.run(task=send_configs_from_file, name="Configuring Banner", file="reader.txt")
  File "/home/ipvzero/Nornir/.venv/lib/python3.10/site-packages/nornir/core/task.py", line 174, in run
    raise NornirSubTaskError(task=run_task, result=r)
nornir.core.exceptions.NornirSubTaskError: Subtask: Configuring Banner (failed)


2023-02-12 07:57:17,763 -  nornir.core -     INFO -        run() - Running task 'banner_push' with args {} on 2 hosts
2023-02-12 07:58:31,473 -  nornir.core -     INFO -        run() - Running task 'banner_push' with args {} on 2 hosts
2023-02-13 04:51:25,654 -  nornir.core -  WARNING -        run() - Task 'banner_push' has not been run â€“ 0 hosts selected
2023-02-13 04:56:12,596 -  nornir.core -     INFO -        run() - Running task 'banner_push' with args {} on 1 hosts
2023-02-13 05:09:59,779 -  nornir.core -     INFO -        run() - Running task 'banner_push' with args {} on 4 hosts
2023-02-13 05:17:28,359 -  nornir.core -     INFO -        run() - Running task 'banner_push' with args {} on 5 hosts
2023-02-13 05:23:04,324 -  nornir.core -     INFO -        run() - Running task 'banner_push' with args {} on 2 hosts
2023-02-13 05:32:25,465 -  nornir.core -     INFO -        run() - Running task 'banner_push' with args {} on 2 hosts
2023-02-13 05:33:02,951 -  nornir.core -     INFO -        run() - Running task 'banner_push' with args {} on 2 hosts
2023-02-13 05:36:32,813 -  nornir.core -     INFO -        run() - Running task 'banner_push' with args {} on 1 hosts
2023-02-13 05:39:13,285 -  nornir.core -     INFO -        run() - Running task 'banner_push' with args {} on 1 hosts
